removed ability for duplicate cards in the scan screen
Redoublet-org/Redoublet-app pull request #11
Opened 2023-03-27 12:12 UTC by TheGoldenFyre

2023-03-28 15:47 UTC, rjvandel commented on src/views/Scan/ViewHandPage.vue
>      .catch(function (error) {
Deze catch krijg ik als ik een foto probeer op te sturen

2023-03-28 15:51 UTC, rjvandel commented
- Ik heb nu dat als ik bij bijv noord twee kaarten toevoeg, confirm en dus terug ga naar scan hands met het overzicht van de gescande handen, dan als ik naar een andere hand ga en vervolgens weer naar noord staat er wel 2/13 maar niks meer op de pagina zelf. Hetzelfde als ik weer terug ga naar noord, waar nogsteeds mn twee kaarten staan, niet confirm, gwn op back druk, dus weer bij het overzicht ben. En dan weer op noord klik, zijn mn kaarten weg. Er staat trouwens dan nog wel op de scan pagina dat ik 2/13 heb.
- Nu kan je wel nog bij twee verschillende handen dezelfde kaarten hebben. Weet niet zeker of het bij deze user story hoort, maar misschien ook nice om te fixen. 
- De back knop op de pagina van scan hands werkt niet helemaal, ik ga nu terug mn hele pad op welke pagina's ik allemaal heb geklikt, ipv naar home. 
- Als ik een foto van kaarten maak en stuur krijg ik een error (zie code welke error)
![image](https://user-images.githubusercontent.com/91630817/228293616-ca4a4df3-e343-4a8d-b3a0-eac3e700322d.png) (geen idee of dit werkt)
Ik weet niet of dat ligt aan dat yolo ze niet detecteerd. Maar anders kunnen we misschien een error geven dat er niks gedetecteerd is? Denk eigenlijk dat het niet daaraan ligt. Misschien kunnen we dan ook gelijk zorgen dat de foto ook weggaat en niet meer op het beeld te zien is (nu als ik terug ga naar scan hands pagina en daarna weer naar deze hand staat de foto er nog).

Sorry erg veel comments <3 
Ik kan het nog niet helemaal goed testen omdat ik de kaart foto niet heb.. Maar dat doe ik zodra jij het doorstuurt :)

2023-03-28 15:53 UTC, rjvandel requested changes
Zie mn comments

2023-03-30 11:22 UTC, rjvandel reviewed
Looks good

2023-03-30 12:39 UTC, rjvandel approved these changes
Hmm

2023-03-30 14:21 UTC, Koekiemonster69 requested changes
-Allereerst (niet echt onderdeel van deze task maar goed) is t denk ik nice als we hier buttons van maken: 
![image](https://user-images.githubusercontent.com/74185498/228857344-bd6958c1-c9a2-4b4c-b719-c10cd519f3ed.png)
-Tweede dingetje de foto die ik invoer geeft terug:
![image](https://user-images.githubusercontent.com/74185498/228859393-fd1f92b2-b35a-4307-9c4e-00fdab33909b.png)
Waarbij er dus 2 keer een T?? wordt gedetecteerd, geen idee hoe dat kan (weet niet hoe relevant dit is voor de taak maar goed, ik dacht toch ff handig om te melden). 
-Daarnaast gaat het ook fout als ik een al geconfirmde hand heropen, en dan via de back knop linksboven (in de app, niet in de browser), terugga, en vervolgens weer die hand heropen, zijn alle gedetecteerde kaarten verdwenen.
-Verder heb ik ook dat als ik op het "?" klik (naast de textbox waar je de value van de kaart in kan voeren), en je daarna probeert weg te klikken, het scherm de eerste 3 keer alleen maar lichter wordt (zonder dat de info box weggaat), zie bijlage:
![image](https://user-images.githubusercontent.com/74185498/228860060-5ce46380-2305-4c15-bf43-551abf251521.png)
![image](https://user-images.githubusercontent.com/74185498/228860129-a2540f2f-0f3b-4b3a-8dbf-87d6f63ea913.png)
![image](https://user-images.githubusercontent.com/74185498/228860169-16557c3e-efe7-493c-801a-b89a9f98bc60.png)
![image](https://user-images.githubusercontent.com/74185498/228860215-c623f5c8-10bb-427f-ae07-180db377f203.png)
Dat gebeurde bij mij toen ik bij elke hand die foto invoerde, en toen weer de eerste hand heropende. 
-Dat vraagteken doet raar, ik had daarnet ook een paar keer dat ik op een vraagteken klikte, maar dat er niks gebeurde, maar dat is inconsistent. Ik heb het nu als ik een foto invoer, confirm, en dan bij de volgende hand op het vraagteken klik (zonder een foto in te voeren).
-Hij laat wel zien hoeveel kaarten hij eruit heeft gehaald wanneer je een nieuwe foto maakt (dus eentje die een oude vervangt), maar niet wanneer je eerst een kaart handmatig invoert, en daarna een foto maakt.
![image](https://user-images.githubusercontent.com/74185498/228866253-2858a41a-e786-4d08-b1ca-499d8330f00f.png)

2023-03-30 14:28 UTC, TheGoldenFyre commented
> -Allereerst (niet echt onderdeel van deze task maar goed) is t denk ik nice als we hier buttons van maken:
> ![image](https://user-images.githubusercontent.com/74185498/228857344-bd6958c1-c9a2-4b4c-b719-c10cd519f3ed.png)

Prima! Kunnen we voor volgende week als task meenemen

2023-03-30 14:30 UTC, TheGoldenFyre commented
> Waarbij er dus 2 keer een T?? wordt gedetecteerd, geen idee hoe dat kan (weet niet hoe relevant dit is voor de taak maar goed, ik dacht toch ff handig om te melden).

Dit klopt, want de T die gedetecteerd wordt is anders (harten vs ruiten). Qua detectie gaat dat niet goed, maar qua functionaliteit is dit wel wat we zouden verwachten

2023-03-30 14:32 UTC, TheGoldenFyre commented
> -Verder heb ik ook dat als ik op het "?" klik (naast de textbox waar je de value van de kaart in kan voeren), en je daarna probeert weg te klikken, het scherm de eerste 3 keer alleen maar lichter wordt (zonder dat de info box weggaat), zie bijlage:

Hm bij mij werkt die wel gewoon, misschien is dat ionic die gewoon een beetje quirky doet. Lijkt me handig om in het achterhoofd te houden, dan kunnen we er misschien later nog naar kijken als dit ook op mobile devices niet werkt.

2023-03-30 14:33 UTC, TheGoldenFyre commented
> -Hij laat wel zien hoeveel kaarten hij eruit heeft gehaald wanneer je een nieuwe foto maakt (dus eentje die een oude vervangt), maar niet wanneer je eerst een kaart handmatig invoert, en daarna een foto maakt.

Het lukt me ook niet om dit na te bootsen, als het goed is vervangt een foto alle voorgaande detecties en laat die alleen zijn eigen verwijderde kaarten zien, en dat lijkt bij mij wel te werken?

2023-03-30 14:51 UTC, Koekiemonster69 commented
> > -Hij laat wel zien hoeveel kaarten hij eruit heeft gehaald wanneer je een nieuwe foto maakt (dus eentje die een oude vervangt), maar niet wanneer je eerst een kaart handmatig invoert, en daarna een foto maakt.
> 
> Het lukt me ook niet om dit na te bootsen, als het goed is vervangt een foto alle voorgaande detecties en laat die alleen zijn eigen verwijderde kaarten zien, en dat lijkt bij mij wel te werken?

Oeps, ja je hebt gelijk, ik had niet door dat er zoiezo dubbele zaten in de 2e foto, mb!

2023-03-30 14:51 UTC, Koekiemonster69 reviewed
Lekker bezig!

2023-03-30 14:52 UTC, Koekiemonster69 approved these changes
Nice!

2023-03-30 17:00 UTC, merged

2023-04-16 12:11 UTC, Koekiemonster69 commented
> > Waarbij er dus 2 keer een T?? wordt gedetecteerd, geen idee hoe dat kan (weet niet hoe relevant dit is voor de taak maar goed, ik dacht toch ff handig om te melden).
> 
> Dit klopt, want de T die gedetecteerd wordt is anders (harten vs ruiten). Qua detectie gaat dat niet goed, maar qua functionaliteit is dit wel wat we zouden verwachten

Oh wauw, ik zit nu een bridge cursus te doen, en zie nu pas dat t normaal is om een T neer te zetten in plaats van een 10, dat was wat ik niet begreep haha
![image](https://user-images.githubusercontent.com/74185498/232308987-9b4301e9-3faf-4646-ba4c-ee99a07768b7.png)