Feature 148 overlay card hitbox
Redoublet-org/Redoublet-app pull request #13
Opened 2023-03-29 12:31 UTC by TheGoldenFyre

Scan page now shows hitboxes overlayed over de cards.

2023-03-29 15:13 UTC, Koekiemonster69 reviewed
lekker bezig! paar kleine dingetjes die nog ff gefixt moeten worden

2023-03-29 15:13 UTC, Koekiemonster69 commented on src/views/Scan/ViewHandPage.vue
> +      <div v-if="savedPhoto != undefined" style="width: 90vw">
dit is zodat je nog een kleine margin houdt aan de rand van t scherm of?

2023-03-29 15:13 UTC, Koekiemonster69 commented on src/views/Scan/ViewHandPage.vue
> +document.getElementById("canvas")?.addEventListener("load", () => console.log("uwu"))
haha ondanks dat ik t een prachtige console.log vindt, deze mss toch ff weghalen

2023-03-29 15:13 UTC, Koekiemonster69 commented on src/views/Scan/ViewHandPage.vue
> +  // canvas.setAttribute("style", `background: url('${savedPhoto.webviewPath}')`);
Nitpick: volgens mij is t nice als je dit soort comments weghaalt (maar ik ben hier zelf ook zeker schuldig aan)

2023-03-29 15:13 UTC, Koekiemonster69 commented on src/views/Scan/ViewHandPage.vue
> +    const confidenceText = shortDisplay(detection.card) + ` ${(detection.confidence * 100).toFixed(0)}%`
Nice, volgens mij zei Christiaan in vorige meeting (volgens notulen) dat ie t liefst wilde dat de kaarten conditional gefilterd werden op percentage (dus bijvoorbeeld kaarten < 50% confidence rood, 50 < x < 75 dan geel, hoger dan 75 groeen), maar weet niet of dat al onderdeel is van dit taakje

2023-03-30 09:43 UTC, TheGoldenFyre commented on src/composables/useCamera.ts
> +  return new Promise (function (resolved) {
Yess klopt, Promises worden over het algemeen gebruikt voor code die een tijdje gaat duren om te runnen maar wat wel in de achtergrond kan gebeuren

2023-03-30 09:44 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +      <div v-if="savedPhoto != undefined" style="width: 90vw">
Oeps, die is niet helemaal nodig, die ga ik even aanpassen!

2023-03-30 09:47 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +    const confidenceText = shortDisplay(detection.card) + ` ${(detection.confidence * 100).toFixed(0)}%`
Goeie, die zal ik nog even toevoegen

2023-03-30 14:04 UTC, rjvandel commented
- Hoe werkt het met duplicates eruit halen? Zal hij dan wel meerdere hitboxen laten zien?
- En is er een mogelijkheid dat het in de toekomst sneller wordt door beter trainen? Het duurt nu een stuk langer voordat de detection terug is. Is het anders een idee om al de detections te geven en later pas de foto met confidence boxes?

2023-03-30 14:07 UTC, rjvandel commented on src/views/Scan/ViewHandPage.vue
> +    const box = detection.boundingBox;
; erachter

2023-03-30 14:09 UTC, rjvandel commented on src/composables/useCamera.ts
> +    const i = new Image()
;

2023-03-30 14:10 UTC, rjvandel commented on src/composables/useCamera.ts
> +    i.src = base64Image
;

2023-03-30 14:11 UTC, rjvandel requested changes
zie naai comments, voorderest erg nice!

2023-03-30 14:14 UTC, rjvandel approved these changes
bedankt xoxo

2023-03-31 09:47 UTC, merged