2vs2
Redoublet-org/Redoublet-app pull request #14
Opened 2023-03-29 16:02 UTC by rubenfranquinet

- Added the single table pages that were missing.
- Added Pinia store and made a first store storing a list of boards.
- In a later task the scan page will also store its data in a pinia store and the dds request will take the information from the store.
- All the score related logic is left out since the score will be added in a later task.

2023-03-30 11:48 UTC, rjvandel commented
Deze twee comments zijn niet perse naar jou gericht, maar hoort denk ik wel bij de user story :)
- Als er niks in wordt gevuld bij eerste pagina, een foutmelding geven dat een persoon alle velden moet invullen. Of button discarden als er niet overal wat staat
- Extra back button kan wel weg op eerste page van single table (misschien ook titel geven aan deze page)

2023-03-30 11:50 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
>          <ion-label>Result</ion-label>
Aangeven wat er wordt verwacht, ik had zelf geen idee hihaho

2023-03-30 11:56 UTC, rjvandel commented
- Is het mogelijjk om bij scan page een andere button te hebben dan to gamedetails? Anders misschien beter om die button een andere naam te geven.
- Als ik bij single table terug ga en weer op single table druk moet ik opnieuw de namen invullen etc. Als ik op finished druk na dds dan staan al de oude waardes er nog

2023-03-30 12:01 UTC, rjvandel commented
Ik kom niet meer weg van score table :(

2023-03-30 12:07 UTC, rjvandel commented on src/views/Scan/DDSPage.vue
> +console.log("goeie pagina")
kan weg

2023-03-30 12:10 UTC, rjvandel requested changes
Zie comments

2023-03-30 12:54 UTC, TheGoldenFyre reviewed
Alleen wat kleine nitpicks

2023-03-30 12:54 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
> +
Nitpick: witregel

2023-03-30 12:54 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
> +
Nitpick: witregel

2023-03-31 09:49 UTC, rjvandel commented
Op EnterBoardPage krijg ik nog verschillende errors

2023-03-31 10:39 UTC, rjvandel commented on src/views/SingleTableTournament/SingleTableScore.vue
> +import { InfoValuesForDDS } from "./DDSInfo";
dit moet volgens mij /scan/DDSInfo zijn

2023-03-31 10:43 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +  const boardToBeAdded : Board = {
Dit zijn allemaal geen goede waardes, stuur mij ff berichtje als je hier aan gaat, heb dit op mijn branch al aangepast

2023-04-05 08:25 UTC, TheGoldenFyre reviewed
Zie comments, qua functionaliteit een paar kleine dingen en een paar nitpicks

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
Vlgm kan de "Next board" knop op deze pagina gelijk doorlinken naar de game details page, want de spelers blijven hetzelfde

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
Misschien kunnen we hier ook iets van een finished knop toevoegen die ook alle opgeslagen 2v2 data reset

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
>          </ion-text>
Contract value hier moet nog -6

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
>          </ion-text>
Contract value hier moet nog -6

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
>          </ion-text>
Imp lijk nog niet berekend te worden aan de hand van de ref scores

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScoreTable.vue
> +        </ion-row>
Ref score en imp worden nog niet geset

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/models/board.ts
> +    trump: Suit;
Moet hier niet doubled/vulnerable nog bij? Is eventueel ook iets voor een refactor als je het niet nodig hebt voor je implementatie

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/models/direction.ts
>    switch (dir) {
Misschien functie naam aanpassen

2023-04-05 08:25 UTC, TheGoldenFyre commented on src/views/Scan/DDSPage.vue
> +import { InfoValuesForDDS } from '../../models/DDSInfo';
Misschien beter als je dit importeert als "@/models/ddsinfo"

2023-04-05 09:52 UTC, rubenfranquinet commented on src/views/SingleTableTournament/SingleTableScoreTable.vue
> +        </ion-row>
Imp zal ik inderdaad even fixen, maar hoe willen we de ref score bepalen? Dat ligt aan hoe andere mensen ditzelfde spel gespeeld hebben toch?

2023-04-25 09:54 UTC, rjvandel commented
- De knop "Go to score" na het scannen nog op uit zetten. Nu kan je er wel op klikken en krijg ik allemaal errors in de console. (als ik vervolgens op "debug add cards" klik en daarna op "go to score" is het nogsteeds kapot

2023-04-25 09:58 UTC, rjvandel commented on src/views/SingleTableTournament/SingleTableScoreTable.vue
>    IonBackButton,
IonGrid, IonRow, IonCol toevoegen

2023-04-25 10:06 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +        <ion-select v-model="vulnerable" id="vulnerable" placeholder="Select vulnerability">
Deze ook doen met v-for en sides?

2023-04-25 10:09 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +        <ion-select v-model="trump" id="trump" placeholder="Enter Trump Suit">
deze met v-for

2023-04-25 10:11 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +
witregel

2023-04-25 10:36 UTC, rjvandel commented on src/views/Scan/GameDetailsPage.vue
> +const sides = ref(["North", "South", "East", "West"]);
Moet ht een ref zijn als het niet veranderd?

2023-04-25 10:43 UTC, rjvandel requested changes
zie comments

2023-04-29 14:28 UTC, rjvandel requested changes
> * De knop "Go to score" na het scannen nog op uit zetten. Nu kan je er wel op klikken en krijg ik allemaal errors in de console. (als ik vervolgens op "debug add cards" klik en daarna op "go to score" is het nogsteeds kapot
> * Ik kan nu wel meer dan 13 handen scannen, maar volgens mij is dit gefixed op een andere branch

Alleen deze nog fixen

2023-05-02 09:31 UTC, TheGoldenFyre commented
@rjvandel laatste opmerkingen zijn gefixt! (meer dan 13 is idd in een andere branch al verwerkt)

2023-05-02 09:53 UTC, rubenfranquinet reviewed
Hoop errors bij finishen van de single table. Doet geen schade, maar misschien netjes om te kijken of we de pagina's in cache kunnen verwijderen als we klaar zijn,

2023-05-02 09:53 UTC, rubenfranquinet commented on src/views/SingleTableTournament/SingleTableScore.vue
> +<!-- eslint-disable @typescript-eslint/no-non-null-assertion -->
Is dit nog nodig?

2023-05-03 13:23 UTC, TheGoldenFyre commented
> Hoop errors bij finishen van de single table. Doet geen schade, maar misschien netjes om te kijken of we de pagina's in cache kunnen verwijderen als we klaar zijn,

@rubenfranquinet Cache cleanen lijkt niet eenvoudig te kunnen, dus ik denk dat we dit beter even kunnen laten

2023-05-03 13:35 UTC, rjvandel approved these changes

2023-05-03 13:36 UTC, TheGoldenFyre approved these changes
wat een geile code deze man is lekker bezig

2023-05-03 13:45 UTC, merged