Dealer info toegevoegd
Redoublet-org/Redoublet-app pull request #15
Opened 2023-03-30 13:48 UTC by rjvandel

Nu wordt er een pbn gegenereerd aan de hand van de kaarten en ingevulde info bij game details

2023-03-30 13:55 UTC, TheGoldenFyre requested changes
Ziet er over t algemeen goed uit!

2023-03-30 13:55 UTC, TheGoldenFyre commented on src/views/Scan/GameDetailsPage.vue
> +      ?.value) as Direction,
Is dit misschien te doen met behulp van v-model?

2023-03-30 13:55 UTC, TheGoldenFyre commented on src/views/Scan/DDSPage.vue
>      });
comment eruit

2023-03-30 13:55 UTC, TheGoldenFyre commented on src/models/direction.ts
> +}
misschien charToDirection noemen aangezien je ook andere strings van een direction kan maken

2023-03-30 13:55 UTC, TheGoldenFyre commented on src/views/Scan/DDSPage.vue
> +
console logje eruit

2023-03-30 14:40 UTC, rjvandel commented on src/views/Scan/GameDetailsPage.vue
> +      ?.value) as Direction,
Goeie!

2023-03-30 14:45 UTC, TheGoldenFyre approved these changes
Das war wirklich wunderbar

2023-03-31 07:33 UTC, MatthijsdeHeus requested changes
De app ziet er erg nice uit!

Nog wel een paar comments/vragen die ook meer gaan over de algemene structuur van de code dus is niet echt specifiek voor deze PR.

2023-03-31 07:33 UTC, MatthijsdeHeus commented on src/views/Scan/DDSPage.vue
>  import axios from 'axios';
Is er een reden dat we axios gebruiken t.o.v. fetch?

2023-03-31 08:09 UTC, rjvandel commented
@TheGoldenFyre Misschien kunnen wij maandag even naar deze comments kijken?

2023-03-31 10:36 UTC, TheGoldenFyre commented
> @TheGoldenFyre Misschien kunnen wij maandag even naar deze comments kijken?

Lijkt me prima, ik denk dat qua architectuur Matthijs wel wat goeie opmerkingen maakt die we kunnen aanpassen

2023-03-31 10:37 UTC, TheGoldenFyre commented on src/views/Scan/DDSPage.vue
>  import axios from 'axios';
Ik ga heel eerlijk zijn, dat komt alleen omdat axios het eerste resultaat op google was als je zoekt naar "js post request"

2023-03-31 12:15 UTC, MatthijsdeHeus commented on src/views/Scan/DDSPage.vue
>  import axios from 'axios';
Hahah helemaal goed hoor

2023-03-31 15:30 UTC, rjvandel commented on src/views/Scan/DDSInfo.ts
>  }
Gefixed! Alleen direction zit er nog in maar daarvan is een dubbele. Dat is er in een andere PR uit gehaald

2023-04-03 07:50 UTC, MatthijsdeHeus approved these changes

2023-04-03 08:10 UTC, merged