Feature 136 scoring table
Redoublet-org/Redoublet-app pull request #16
Opened 2023-04-01 14:20 UTC by TheGoldenFyre

Scoring tabel code toegevoegd. Als het goed is kan deze samengevoegd worden met de 2v2 zodat we de volledige weergave kunnen maken!

2023-04-01 14:51 UTC, Stayutazen requested changes
Zie comments

2023-04-01 14:51 UTC, Stayutazen commented on src/models/board.ts
> +}
Willen we de benaming van de enum consistent hebben tussen de website en app?

2023-04-01 14:51 UTC, Stayutazen commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +      <page-title :title="'Board #' + 1"></page-title>
boardNumber lijkt me beter dan een constante gebruiken

2023-04-01 14:51 UTC, Stayutazen commented on src/views/SingleTableTournament/SingleTableScore.vue
>    }
StringToSuit bestaat al, kun je die niet beter aanroepen en vervolgens (StringToSuit() as number) gebruiken ipv StringToInt?

2023-04-01 14:51 UTC, Stayutazen commented on src/views/SingleTableTournament/SingleTableScore.vue
> +const vulnerableEW = true;
Waarom worden deze values al ingevuld?

2023-04-01 17:14 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +      <page-title :title="'Board #' + 1"></page-title>
ik heb nu (denk ik) het board nummer toegevoegd

2023-04-01 17:17 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
>    }
gefixt

2023-04-01 17:23 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/SingleTableScore.vue
> +const vulnerableEW = true;
heb waardes geïnlined, werd alleen gebruikt om de waarde van het optimale contract te bepalen.

2023-04-03 08:20 UTC, rubenfranquinet approved these changes
Ziet er prima uit, zeker als het straks nog eens door een PR heen gaat

2023-04-03 08:23 UTC, merged