Feature 162 pinia
Redoublet-org/Redoublet-app pull request #18
Opened 2023-04-15 07:27 UTC by rubenfranquinet

Belangrijk bij het reviewen:

- Check of alles nog werkt.
- Zijn er nog meer stores nodig?
- Is de boards store nu hoe we het willen?
- Zijn er stukken code die niet meer gebruikt worden omdat we nu met een store werken?

2023-04-15 08:55 UTC, rjvandel commented
- Scannen gaat goed, alleen blijft er staan: "More than 10 cards not scanned". Als er een kaart mist wordt dat ook niet aangegeven. Als er een kaart dubbel is wordt het **wel** aangegeven. Ik kan ook gewoon doorklikken als niet alle kaarten zijn gescaned (ik weet niet of dit allemaal al goed was op deze branch).
- De vulnerability en dealer info wordt niet meegegeven nadat je op calculate dds klikt. Bij de game info staat nu gwn 0 voor beide. 
- Als je finished na de dds analyse en weer wilt scannen zijn dezelfde waardes er nog voor alle kaarten. Zelfde geldt voor Join Tournament. 
- Ik krijg deze error als ik klaar ben bij New Tournament: 
![image](https://user-images.githubusercontent.com/91630817/232202563-4cc3825c-4194-44da-82cc-c95bd82e1c9d.png)

2023-04-15 09:35 UTC, rjvandel commented on src/stores/boards.ts
Is het niet dat je de dingen in de defineStore onderverdeeld in state, actions en getters? Waarbij hier in de state je dus een lijst van lege boards maakt. Actions bevat de functie resetBoards en getters bevat getNewest.

2023-04-15 09:37 UTC, rjvandel commented on src/views/HomePage.vue
> +  const boardToBeAdded: Board = {
Misschien mooier om dit apart ergens te definieren als een soort beginBoards ofzo

2023-04-15 09:41 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +        value: 0,
Kan deze functie niet ook mbv boardStore?

2023-04-15 09:42 UTC, rjvandel commented on src/views/Scan/ViewHandPage.vue
> +      console.log(board);
mag weg

2023-04-15 09:49 UTC, rjvandel commented on src/composables/deckAnnotation.ts
> +export function getMissingCards(cards: Card[]): Card[] {
Deze functie werkt niet gok ik

2023-04-15 10:17 UTC, TheGoldenFyre commented on src/composables/deckAnnotation.ts
> +export function getMissingCards(cards: Card[]): Card[] {
Vlgm heb ik dit kapot gemaakt tijdens mn pinia fixes, dus heb dit ff gefixed

2023-04-15 10:31 UTC, TheGoldenFyre requested changes
Voor functionaliteit zie comment Roos, al had ik geen last van het feit dat kaarten in de scan page bleven staan. Verder vooral kleine nitpicks

2023-04-15 10:31 UTC, TheGoldenFyre commented on src/composables/analysesDDS.ts
> +    const boards = useBoardsStore();
Misschien iets van een comment toevoegen / naam veranderen van de functie om aan te geven dat deze direct het meest recente bord uit de store aanpast?

2023-04-15 10:31 UTC, TheGoldenFyre commented on src/composables/handPBN.ts
> +// }
Comments weghalen

2023-04-15 10:35 UTC, rjvandel requested changes
zie comments

2023-04-20 07:04 UTC, TheGoldenFyre commented
Aangezien Ruben nog even in Frankrijk zit neem ik het implementeren van de comments voor deze PR even over

2023-04-20 08:05 UTC, TheGoldenFyre approved these changes
wow wat een goede changes! we moeten die author echt loonsverhoging geven

2023-04-20 09:00 UTC, rjvandel commented on src/views/SingleTableTournament/SingleTableScore.vue
>      //TODO: Get DDS from store and show it instead of default values.
weg

2023-04-20 09:01 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
>  import { Board, Doubled, Vulnerable, stringToDoubled, stringToVulnerable, isVulnerable } from '../../models/board';
weg wat niet gebruikt wordt

2023-04-20 09:02 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +  const dec = stringToDirection(declarer.value);
denk toch andere naam geven...

2023-04-20 09:52 UTC, rjvandel commented on src/views/Scan/DDSPage.vue
> +            <p>Vulnerability: {{ vulnerableToString(board.vulnerable) }}</p>
misschien dit wel gwn naar East/West ipv ew

2023-04-20 09:53 UTC, rjvandel commented on src/views/Scan/GameDetailsPage.vue
> +          <ion-select-option :value="item" v-for="item of sides" :key="item">{{
andere naam voor item?

2023-04-20 09:53 UTC, rjvandel commented on src/views/Scan/GameDetailsPage.vue
>  import { InfoValuesForDDS } from "../../models/DDSInfo";
weg

2023-04-20 09:57 UTC, rjvandel commented on src/composables/analysesDDS.ts
> +  // TODO: Dealer/declarer/whatevs uitvinden
deze comments kunnen weg toch?

2023-04-20 09:58 UTC, rjvandel requested changes
Zie comments :)

2023-04-20 11:19 UTC, rjvandel commented on src/views/SingleTableTournament/SingleTableScore.vue
>  const bestContractEW = getBestContract(playerContracts.E);
Kan const sampleContracts weg? Verder kunnen bij de imports nog aardig wat dingetjes weg

2023-04-20 11:26 UTC, rjvandel commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +  board.vulnerable = vulnerabilityValue,
Misschien gaat het hier fout met de error die ik krijg?

2023-04-20 11:27 UTC, rjvandel commented
Als ik op calculate DDS klik krijg ik deze error: 
![image](https://user-images.githubusercontent.com/91630817/233352233-d8ace65b-ea5d-477c-bd85-969eb2b3f947.png)

2023-04-20 11:28 UTC, rjvandel requested changes
Bijnaaaa

2023-04-20 13:06 UTC, TheGoldenFyre commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +  board.vulnerable = vulnerabilityValue,
error blijkt te komen omdat de backend was gecrashed :')

2023-04-22 14:29 UTC, TheGoldenFyre commented
Aangezien de enige resterende issue hier een probleem was met de backend zelf, merge ik met een "missende" approve

2023-04-22 14:29 UTC, merged