extracted functions from models to helper files
Redoublet-org/Redoublet-app pull request #19
Opened 2023-04-17 13:53 UTC by sebas42069

Is de file structuur goed zo of zou de helper folder buiten de models folder moeten?
Zijn de functies zo goed onderverdeeld? (gewoon per file wat ze gebruikten in models naar hun eigen file).
werkt de app nog zoals hiervoor?

2023-04-18 10:06 UTC, TheGoldenFyre commented
Misschien is het een idee om hier ook gelijk de kans te nemen om onze naming scheme wat meer consistent te krijgen, voor modellen PascalCase en voor helper / composable functies kebab-case?

2023-04-18 10:10 UTC, TheGoldenFyre requested changes
Qua functionaliteit en code ziet alles er goed uit, zie alleen comment hierboven

2023-04-18 11:39 UTC, rjvandel commented on src/views/Scan/DDSPage.vue
> +                                                as PossibleContract, showTotalTricks) }}
Ik krijg errors als deze line zo komt te staan, alleen als het op dezelfde line staat gaat het goed..?

2023-04-18 11:40 UTC, rjvandel commented on src/views/Scan/DDSPage.vue
> +                        {{ DisplayValue((playerContracts as ContractsPerPlayer).W.find(contract => contract.trump == trump)
geldt voor deze allemaal

2023-04-18 11:40 UTC, rjvandel commented on src/views/Scan/DDSPage.vue
> +import { DisplayValue } from "@/helpers/possible-contractHelper";
deze met '' ipv ""

2023-04-18 11:41 UTC, rjvandel commented on src/views/Scan/GameDetailsPage.vue
>  import { useRouter, Router } from "vue-router";
is misschien code clean up dingetje maar soms doen we " " en soms ' '

2023-04-18 11:42 UTC, rjvandel commented on src/views/Scan/GameDetailsPage.vue
>            Calculate DDS
dit ook mee op de vorige line?

2023-04-18 11:44 UTC, rjvandel commented on src/models/ScanDirections.ts
>    location: string;
Misschien deze hele interface gwn bij direction

2023-04-18 11:45 UTC, rjvandel commented on src/helpers/scanDirectionsHelper.ts
> +import { ScanDirection } from "../models/ScanDirections";
dit dan ook allemaal bij directionHelper

2023-04-18 11:48 UTC, rjvandel commented on src/models/TableInformation.ts
>      ReferenceTable,
dit allemaal samen met card?

2023-04-18 11:49 UTC, rjvandel requested changes
Zie mn comments :)

2023-04-24 15:45 UTC, sebas42069 commented on src/views/Scan/DDSPage.vue
> +                                                as PossibleContract, showTotalTricks) }}
Hij staat nu weer op een regel

2023-04-25 10:29 UTC, sebas42069 commented on src/views/Scan/DDSPage.vue
> +                                                as PossibleContract, showTotalTricks) }}
heb het op een line gezet

2023-04-25 10:29 UTC, sebas42069 commented on src/views/Scan/DDSPage.vue
> +                        {{ DisplayValue((playerContracts as ContractsPerPlayer).W.find(contract => contract.trump == trump)
hier ook

2023-04-25 10:30 UTC, sebas42069 commented on src/views/Scan/DDSPage.vue
> +import { DisplayValue } from "@/helpers/possible-contractHelper";
aangepast

2023-04-25 10:30 UTC, sebas42069 commented on src/views/Scan/GameDetailsPage.vue
>  import { useRouter, Router } from "vue-router";
aangepast

2023-04-25 10:31 UTC, sebas42069 commented on src/helpers/scanDirectionsHelper.ts
> +import { ScanDirection } from "../models/ScanDirections";
gedaan

2023-04-25 10:31 UTC, sebas42069 commented on src/models/possible-contract.ts
>    trump: string;
gedaan

2023-04-25 10:31 UTC, sebas42069 commented on src/models/TableInformation.ts
>      ReferenceTable,
deze hoeft niet vind ik

2023-04-28 16:37 UTC, TheGoldenFyre approved these changes

2023-04-29 14:33 UTC, rjvandel commented on src/models/DDSInfo.ts
> +import { Direction } from "@/models/Direction";
Ik krijg hier errors omdat bij mij de model gwn nog direction heet?

2023-04-29 14:37 UTC, rjvandel requested changes
Zie laatste ding, weet niet of dat alleen bij mij is?

2023-05-10 12:14 UTC, rjvandel approved these changes
okidoki

2023-06-13 09:11 UTC, closed without merging