Vertaling van oplevering naar Nederlands gedaan
Redoublet-org/Redoublet-app pull request #20
Opened 2023-04-17 15:26 UTC by TheGoldenFyre

Alle nodige delen voor oplevering zijn vertaald naar het Nederlands. Mocht er nog iets grammaticaal misgaan / heb ik iets over het hoofd gezien, laat het weten!

2023-04-18 11:05 UTC, rjvandel commented on src/views/HomePage.vue
> +        <ion-title>Start</ion-title>
Misschien een andere titel?

2023-04-19 12:34 UTC, rjvandel commented on src/views/Scan/ScanPage.vue
>            {{ nonScannedCards(reactiveDetections).map(deckUsage => shortDisplay(deckUsage.card)).join(", ") }}</h3>
Misschien volluit schrijven ipv O,W? Of is dat heel veel gezeik

2023-04-19 12:36 UTC, rjvandel commented
Nog twee dingetjes: 
- de back buttons moeten ook nog naar "terug"
- Als ik nu druk op klaar of op back gaat hij niet terug: 

![image](https://user-images.githubusercontent.com/91630817/233076702-86aa1d60-fc85-462c-b885-6c12258232e8.png)

2023-04-19 12:38 UTC, rjvandel requested changes
Looks good, nog paar puntjes

2023-04-19 15:44 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +        <ion-label>Kleur</ion-label>
Van https://westlandsebc.nl/praktijk/bridgetermen.php: 
![image](https://user-images.githubusercontent.com/20602812/233129157-f515380e-625a-4a67-83b5-36f8942da62e.png)
Ik vind het zelf ook vaag, maar suit vertaalt blijkbaar naar kleur

2023-04-19 15:49 UTC, TheGoldenFyre commented on src/views/Scan/ScanPage.vue
>            {{ nonScannedCards(reactiveDetections).map(deckUsage => shortDisplay(deckUsage.card)).join(", ") }}</h3>
Gedaan!

2023-04-20 07:47 UTC, rjvandel approved these changes
Noiceee

2023-04-20 11:17 UTC, MatthijsdeHeus reviewed
Ik zie niet precies waar het staat maar bij de analyse staat er nog "select dealer".

2023-04-20 11:18 UTC, MatthijsdeHeus commented
Klaar knop heeft de verkeerde link

2023-04-20 11:20 UTC, MatthijsdeHeus commented
Nitpick: bij de popups staan nog "OK" en "CANCEL".

2023-04-20 11:36 UTC, MatthijsdeHeus approved these changes

2023-04-20 12:12 UTC, merged