optie voor debug knop
Redoublet-org/Redoublet-app pull request #24
Opened 2023-04-24 14:30 UTC by rjvandel

2023-04-28 16:38 UTC, TheGoldenFyre requested changes
Zie alleen de ene comment

2023-05-01 09:18 UTC, rubenfranquinet reviewed
Ziet er goed uit. Comment van Thomas lijkt me inderdaad wel een goed idee.

2023-05-01 09:21 UTC, rubenfranquinet approved these changes
Mocht de comment van Thomas te veel werk zijn zou ik dat niet doen en gewoon mergen. Is tenslotte functionaliteit die de gebruikers toch niet te zien krijgen.

2023-05-02 15:10 UTC, rjvandel commented on src/views/Scan/ViewHandPage.vue
> +
Jaa kan zeker, ik heb nu allen dat hij dan op de scanPage zelf niet laat zien dat er 13 kaarten overal gescanned zijn dan. Dus dan ga je gelijk door naar game details. Misschien is het een idee dat we beide er in houden? Dan kan het gebruikt worden om gewoon snel door te gaan naar dds, maar ook om te checken of er geen dubbele zijn gescanned. Voor mn gevoel moet ik anders veel functies over gaan zetten naar ScanPage als ik daar met die debug knop ook wil testen of er duplicates zijn etc.

2023-05-02 16:25 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +
Opzich zou je er bij de debug knop ook van uit kunnen gaan dat alles gewoon werkt, zeker aangezien we het alleen zelf gebruiken. Dan hoef je minder over te zetten.
Beide houden lijkt me overigens wel een goed idee, al zou ik dan een aparte fillInHand functie maken die alleen die specifieke hand vult voor de ViewHand pagina en dan deze gebruiken voor ScanPage

2023-05-03 11:30 UTC, rubenfranquinet submitted a review, later dismissed

2023-05-04 07:05 UTC, rjvandel commented on src/views/Scan/ViewHandPage.vue
> +
Dat is nu het geval toch?

2023-05-04 13:17 UTC, TheGoldenFyre submitted a review, later dismissed

2023-05-11 08:37 UTC, TheGoldenFyre approved these changes

2023-05-11 08:39 UTC, Nightshades24 approved these changes
Opnieuw een approve namens ruben

2023-05-11 08:39 UTC, merged