Feature 167 testing volledig dek
Redoublet-org/Redoublet-app pull request #26
Opened 2023-04-25 13:36 UTC by TheGoldenFyre

2023-04-30 11:49 UTC, rjvandel commented on tests/unit/deckAnnotation.spec.ts
> +            card: {
Mooie functie!

2023-04-30 11:52 UTC, rjvandel commented on tests/unit/deckAnnotation.spec.ts
> +    test("multiScannedCards ignores duplicates within single hand", () => {
Ik snap deze niet helemaal. Geven twee duplicates in dezelfde hand niet deze error? Omdat het op de scan pagina zelf al wordt aangegeven?

2023-04-30 12:23 UTC, rjvandel requested changes
Ziet er goed uit! Denk dat de tests die je hebt geschreven voldoende zijn. Zouden we misschien nog meer e2e tests willen? 

Verder heb ik trouwens dat mijn e2e test niet werkt 
![image](https://user-images.githubusercontent.com/91630817/235352782-61882c6d-9c06-4317-a515-6bae4e7697bc.png)

2023-05-02 08:45 UTC, TheGoldenFyre commented on tests/unit/deckAnnotation.spec.ts
> +    test("multiScannedCards ignores duplicates within single hand", () => {
Handmatige input blokkeert dit inderdaad, maar van de kaartdetectie kan je wel technisch gezien meerdere duplicaten in een hand krijgen. Mocht de filtering daar fout gaan is het niet multiScannedCards zijn verantwoordelijkheid om dit te valideren, dus ik dacht dat kan deel zijn van een test

2023-05-02 13:01 UTC, TheGoldenFyre commented
> Zouden we misschien nog meer e2e tests willen?

Ik zal er wel eentje toevoegen om te kijken of de button van disabled gaat op het moment dat je alle kaarten invult

2023-05-02 13:01 UTC, TheGoldenFyre commented
> Verder heb ik trouwens dat mijn e2e test niet werkt 

Hm interessant, moet je maar een keertje laten zien op kantoor!

2023-05-03 10:32 UTC, rjvandel submitted a review, later dismissed
noice

2023-05-10 10:24 UTC, sebas42069 approved these changes
noice x2

2023-05-18 21:10 UTC, closed without merging

2023-05-18 21:10 UTC, TheGoldenFyre commented
Pull request tijdelijk gesloten aangezien de prioriteit van de app op het moment bij kaartdetectie ligt