Feature 205&207 duidelijk voor user
Redoublet-org/Redoublet-app pull request #32
Opened 2023-05-01 09:33 UTC by rjvandel

Gedaan

Knoppen verwisseld
Niet op dingen kunnen klikken tijdens laden
T naar 10
Meer uitleg
Ik hoor het graag als dingen nog duidelijker moeten!

2023-05-01 09:51 UTC, rubenfranquinet reviewed
Lekker duidelijk!

Nog een paar kleine comments:
- Op dit moment kan er gescrold worden in de boxes van scan north, scan east, etc. Dit kan het beste even weggehaald worden. Zal iets met margins te maken hebben gok ik.
- Als ik een kaart toevoeg die er al bij staat gebeurt er niks, misschien is een kleine indicatie dat die er al bij zit wel handig.

2023-05-01 09:51 UTC, rubenfranquinet commented on src/views/Scan/ViewHandPage.vue
>          <h3 id="text-image-preview">Neem een foto om detecties kunnen zien!</h3>
Type fout: Neem een foto om detecties **te** kunnen zien!

2023-05-02 16:17 UTC, TheGoldenFyre requested changes

2023-05-02 16:17 UTC, TheGoldenFyre commented on src/models/card.ts
>      case Value.Jack:
Misschien is het handig om hier een tweede functie voor te maken; een functie valueString (met Value.Ten = 10) en pbnChar / valueChar (met Value.Ten = T). Dan hebben we nog steeds een functie voor als een enkel karakter / de echte pbn weergave

2023-05-02 16:17 UTC, TheGoldenFyre commented on src/views/Scan/ScanPage.vue
> +}
Preview foto's worden niet gereset

2023-05-02 16:17 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +      </div>
Typfout: gescand ipv gescanned

2023-05-02 16:17 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +        </div>
Deze knop is nu alleen beschikbaar bij >13 kaarten, maar is dat wel handig? Lijkt me dat je misschien ook opnieuw een foto zou willen maken als er minder kaarten dan dat huidig in je hand staan

2023-05-03 07:53 UTC, rjvandel commented on src/views/Scan/ScanPage.vue
> +}
Jaa klopt, alleen kan dat uberhaupt wel op deze pagina?

2023-05-03 10:15 UTC, TheGoldenFyre commented on src/views/Scan/ScanPage.vue
> +}
Zoals fysiek besproken laten we het resetten van de foto even buiten scope

2023-05-03 10:17 UTC, TheGoldenFyre approved these changes
zeer solide

2023-05-03 11:30 UTC, rubenfranquinet approved these changes

2023-05-03 11:43 UTC, merged