Foto reset
Redoublet-org/Redoublet-app pull request #34
Opened 2023-05-05 15:55 UTC by rjvandel

Nu wordt alles wel gereset als je klaar bent of op terug klikt. 

Fotos worden nu opgeslagen in een store. Ik had wel een paar keer dat fotos soms niet meer zichtbaar waren. Als je bijv na klaar opnieuw ging scannen of als je weer terug kijkt naar een oude hand. De laatste paar keer was dit niet het geval, maar daar vooral op letten!

2023-05-06 12:15 UTC, rubenfranquinet commented
Deze error komt in de console bij het openen van een scan hand pagina. Volgensmij doet dit geen schade, maar is het misschien mogelijk om het te fixen dat deze error niet meer komt?
![image](https://user-images.githubusercontent.com/64008619/236623439-99984813-2503-4c8a-99ad-fad0988db476.png)

2023-05-06 12:25 UTC, rubenfranquinet commented
Ik heb het op meerdere telefoons getest en dit is hoe het eruit ziet op een samsung galaxy S8+. Misschien een idee om de tekst iets kleiner te maken?
![image](https://user-images.githubusercontent.com/64008619/236623869-a4cefa18-0d66-446a-ab21-b0054695a604.png)

2023-05-06 12:36 UTC, rubenfranquinet reviewed
Al met al ziet het er prima uit en werkt het ook helemaal. Ik heb meerdere keren achter elkaar gescand en niet een probleem gehad met foto's die verkeerd of niet waren. Wel moeten we even opletten, shared-detections.ts bestaat namelijk niet meer in main omdat alles daar met stores werkt. Dus dat zal wat merge conflicten opleveren. Maar voor de oplevering ziet het er prima uit.

2023-05-06 12:36 UTC, rubenfranquinet commented on src/views/Scan/ViewHandPage.vue
Deze file bevat een paar stukken met een heleboel enters tussen functies, verwijder die even.

2023-05-06 13:30 UTC, rjvandel commented
> Deze error komt in de console bij het openen van een scan hand pagina. Volgensmij doet dit geen schade, maar is het misschien mogelijk om het te fixen dat deze error niet meer komt? ![image](https://user-images.githubusercontent.com/64008619/236623439-99984813-2503-4c8a-99ad-fad0988db476.png)

Jaa deze heb ik al een poosje, uberhaupt sinds de scan app apart is. Volgens mij weet @TheGoldenFyre hier meer van hehe

2023-05-06 17:08 UTC, TheGoldenFyre requested changes
Afgezien van de comments van Ruben ziet de code er prima uit, ik zal nog ff koekeloeren naar die error

2023-05-06 17:08 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
>          <ion-fab vertical="center" horizontal="center">
Hiervoor zou evt ook  gewoon een v-else kunnen worden gebruikt ipv de v-if="!check"

2023-05-06 17:16 UTC, TheGoldenFyre commented
@rjvandel @rubenfranquinet ik heb net een kleine commit gedaan die de errors in de console weg lijkt te werken, voor de rest zie gwn mn review comments

2023-05-08 08:24 UTC, TheGoldenFyre approved these changes
ziet er goed uit, we moeten miss wel letten op tekstgrootte op kleinere devices in de toekomst want dat kan misgaan met vaste pixelgroottes.

2023-05-09 10:58 UTC, rubenfranquinet approved these changes

2023-05-10 10:48 UTC, merged