Feature 264: Aanpassingsknop voor de detecties
Redoublet-org/Redoublet-app pull request #44
Opened 2023-05-24 10:40 UTC by tvdplas

Detecties in de lijst van de hand hebben nu een aanpassingsknop zodat je direct kan wijzigen ipv verwijderen en dan opnieuw toevoegen. 

Functionaliteit die minimaal getest moet worden voor de pr: 
- Kunnen aanpassingen gedaan worden
- Worden aanpassingen opgeslagen (ook in de store)
- Kunnen aanpassingen dubbele kaarten veroorzaken
- Is de manual add knop nog volledig werkend

2023-05-25 11:29 UTC, rjvandel commented on src/views/Scan/ViewHandPage.vue
> +const editingIndex = ref(-1);
Niet spannend maar vind editingCard logischere naam

2023-05-25 11:33 UTC, rjvandel commented
- Meer uitleg waarom een kaart niet kan worden toegevoegd bij een dubbele. 
- De info over de input format misschien nu bovenaan ergens? Dat 'koning' invullen niet werkt
- De "card not added because it was already in the detections" comment blijft nu staan als je bv door gaat met aanpassingen. Miss mooi als dit weg gaat wanneer een andere knop wordt ingedrukt.
- In mn board wordt de aanpassing als een string gegeven?
<img width="140" alt="image" src="https://github.com/Redoublet-org/Redoublet-app/assets/91630817/26cd0c2c-3bde-4098-99ef-6f4408dd01ac">
- Als ik aanpas en niet bevestig kan ik wel naar andere pagina's etc. Krijg hierdoor errors dat het invalid suit is. Verder wordt als ik dan een nieuwe hand scan deze detections niet opgeslagen.

2023-05-25 11:34 UTC, rjvandel requested changes
zie comments

2023-05-26 11:06 UTC, tvdplas commented
>     Meer uitleg waarom een kaart niet kan worden toegevoegd bij een dubbele.

Ik heb toegevoegd dat je een waarschuwing krijgt als je een dubbele kaart wilt toevoegen

>     De info over de input format misschien nu bovenaan ergens? Dat 'koning' invullen niet werkt

Is dit hier nodig? Aangezien je bij het aanpassen wel ziet dat de weergave van de kaart leidend is voor de invoer? Als we dit wel echt willen, moeten we even puzzelen met hoe we dat er nog bij kunnen proppen. Gezien de nieuwe input format die Christiaan in de pdf heeft doorgestuurd lijkt het me ook niet de hoogste prioriteit.

>     De "card not added because it was already in the detections" comment blijft nu staan als je bv door gaat met aanpassingen. Miss mooi als dit weg gaat wanneer een andere knop wordt ingedrukt.

Is gefixt

>      In mn board wordt de aanpassing als een string gegeven?

Oeps, even vergeten te parsen.

>     Als ik aanpas en niet bevestig kan ik wel naar andere pagina's etc. Krijg hierdoor errors dat het invalid suit is. Verder wordt als ik dan een nieuwe hand scan deze detections niet opgeslagen.

Ik heb er nu voor gezorgd dat je niet de pagina kan verlaten voordat je de edit hebt opgeslagen


Kwam daarnaast ook zelf nog tegen dat het verwijderen van een andere kaart tijdens het editen een beetje buggy is, dus ik heb ervoor gezorgd dat editen wordt gecanceld als je iets verwijderd

2023-05-27 14:56 UTC, rjvandel commented
Ziet er goed uit!

2023-05-27 14:56 UTC, rjvandel approved these changes

2023-05-31 12:23 UTC, rubenfranquinet reviewed
kleine comment, maar verder ziet het er best uit

2023-05-31 12:23 UTC, rubenfranquinet commented on src/views/Scan/ViewHandPage.vue
> +          <template v-if="index != editingCardIndex">
Hebben we hier nou een template in een template? Dat lijkt me niet echt de bedoeling toch, zou dan eerder een div gebruiken

2023-05-31 12:23 UTC, rubenfranquinet commented on src/views/Scan/ViewHandPage.vue
> +          <template v-else>
Dit ook divs ???

2023-05-31 12:25 UTC, rubenfranquinet approved these changes

2023-05-31 12:37 UTC, rubenfranquinet approved these changes

2023-05-31 12:41 UTC, rjvandel approved these changes

2023-05-31 12:42 UTC, merged