Bugfix 333: Rest vertalingen naar Nederlands
Redoublet-org/Redoublet-app pull request #53
Opened 2023-06-12 20:49 UTC by tvdplas

Rest van de gebruikte delen van de app zijn vertaald naar het Nederlands. Alleen de single table sectie en de DDS analyse zijn aangepast, aangezien dit de enige gebruikte delen zijn die we nog niet vertaald hadden tijdens de oplevering. 

Wat moet er getest worden? 
- Is alles vertaald? Let binnen de gebruikte delen (scan enkele hand en nieuw tournament) erop dat _alles_ vertaald is. Dit betekent ook popup windows, dingen als richtingen en scores die door de app worden gegenereerd, en gwn in general alle zichtbare strings.
- Werkt alles nog naar behoren? Vorige vertaling had enkele problemen met richtingen aangezien de waarde direct werd geparsed, maar hier is nu beter op gelet. Miss heb ik echter wat over het hoofd gezien.

2023-06-18 19:23 UTC, sebas42069 requested changes
de login pagina is nog volledig in het engels. (inloggen, registreren, wachtwoord enz.)
tournament = toernooi
Join tournament moet iets zijn zoals 'meedoen aan toernooi' ofzo.

New tournament moet ook veranderd worden naar 'nieuw toernooi'
en er staat nog 'multiple tables', en alles binnen multiple tables is alles ook nog engels.

'go to game details' wanneer alle kaarten gescand zijn

2023-06-18 19:36 UTC, tvdplas commented
@sebas42069 login, join tournament, en multiple tables vallen allemaal buiten scope en worden in een andere PR eruit gesloopt, dus die laat ik ff voor wat t is
Game details en new tournament single table ga ik ff voor je fixen!

2023-06-18 19:53 UTC, sebas42069 requested changes
![image](https://github.com/Redoublet-org/Redoublet-app/assets/72391324/56d496f1-17cd-4fce-91af-79a99dc7d383)
deze 'go to game details' had ik het over in scan enkel bord

2023-06-19 07:30 UTC, tvdplas commented
@sebas42069 bij mij is dat al gefixt?
![image](https://github.com/Redoublet-org/Redoublet-app/assets/20602812/a4d431e9-9c47-4476-8b78-ab3254d187d7)

2023-06-19 10:22 UTC, sebas42069 commented
@tvdplas oh gek, ik zie het ook nu. toppie

2023-06-19 10:22 UTC, sebas42069 approved these changes

2023-06-19 14:48 UTC, merged