Feature 352: styling scanpage dds gamedetails
Redoublet-org/Redoublet-app pull request #65
Opened 2023-06-22 08:48 UTC by tvdplas

Styling van scanpage, dds page voor scan, gamedetails

2023-06-22 09:47 UTC, rjvandel requested changes
SCANPAGE
- Voor de scanpage, misschien is het handig om het lettertype iets groter te maken en de knop iets lichter, dus van de "Scan Zuid (0/13)..." knop. Ik denk dat het nu net iets te moeizaam lezen is. 
- Verder voor de scan pagina: misschien mooi om het te doen zoals bij handlist item, met licht oranje en donker er omheen. Het is denk ik duidelijker om zwarte letters te lezen en de letters wat verder van de rand hebben te staan. Bij "Los de onderstaande problemen op" staat de L erg dicht bij het witte. 
-" voordat u door kunt gaan naar: " met dubbele punt, of linkName niet met hoofdletter. Spel Informatie hoeft denk ik ook niet met hoofdletters.
- Ipv "in Zuid, Noord", "Zuid en Noord" als we dat op een makkelijke manier kunnen fixen, anders boeie
- knop naar Invoer van Spel Informatie, spel informatie in lowercase.

GAME DETAILS:
- Zelfde als bij scanpage met het wit met oranje. Zou het doen zoals bij handlist item. 
- Zou zeggen analyse ipv dds, snappen mensen toch niet. Dus bij de knop en bij het oranje vlak.
- back button -> terug

DDS PAGE
- "Par contracten voor dealer paar met score .." misschien een andere zin? Vind het nu net beetje vaag wat dit is. 
- Lettertype van kwetsbaarheid etc en resultaat mag groter.

2023-06-22 11:38 UTC, rjvandel requested changes
Alleen het grote van lettertype nog. Of hoort dat bij die andere taak?

2023-06-22 20:36 UTC, tvdplas commented
@rjvandel Lettertype was al een tikkie groter gezet, maar ik kan m nog een standje hoger zetten

2023-06-23 07:43 UTC, rjvandel approved these changes
noice

2023-06-23 10:12 UTC, merged