Advies scherm
Redoublet-org/Redoublet-app pull request #66
Opened 2023-06-23 14:01 UTC by rjvandel

Als je wilt gaan scannen komt er eerst een scherm die vertelt hoe je fotos moet maken. Op de scanpagina is er ook een knop waar je nog eens naar dat advies kan kijken.

2023-06-23 20:07 UTC, tvdplas requested changes
Ziet er al heel goed uit! Wel een aantal opmerkingen over de architectuur en een paar nitpicks. 

Daarnaast ook nog wat algemene vragen; 
- Willen we misschien in een store opslaan dat de gebruiker een instructie heeft gehad? Dan kunnen we ervoor zorgen dat je niet meerdere keren het instructiescherm te zien krijgt.
- Willen we het adviesscherm ook laten zien tijdens single table mode, of is de knop op de ViewHandPage dan genoeg? Kan me voorstellen dat single table "advanced" is, dus dat we er dan van uitgaan dat de gebruiker het scherm al een keer heeft gezien.
- Misschien is het een idee om onderaan de instructiepagina nog even te laten zien hoe je de pagina terug kan vinden (iets van een kleine foto van de help button met als tekst dat dit tijdens het scannen gevonden kan worden)

2023-06-23 20:07 UTC, tvdplas commented on src/views/Scan/ViewHandPage.vue
> +}
Is deze functie nodig? Zo ja, misschien een duidelijkere naam, maar opzich kan dit ook gewoon direct in de @click

2023-06-23 20:07 UTC, tvdplas commented on src/views/Scan/ViewHandPage.vue
> +          <ion-icon  :icon="helpOutline"></ion-icon>
(nitpick) formatting
```suggestion
          <ion-icon :icon="camera"></ion-icon>
          <ion-icon :icon="helpOutline"></ion-icon>
```

2023-06-23 20:07 UTC, tvdplas commented on src/views/Scan/ViewHandPage.vue
![image](https://github.com/Redoublet-org/Redoublet-app/assets/20602812/4417e78d-67ef-4d36-92a4-fee9b0557698)
(nitpick) Er is heel weinig witruimte onderaan de modal, misschien mooier als je wat meer margin toevoegt

2023-06-24 10:12 UTC, rjvandel commented
> Ziet er al heel goed uit! Wel een aantal opmerkingen over de architectuur en een paar nitpicks.
> 
> Daarnaast ook nog wat algemene vragen;
> 
> * Willen we misschien in een store opslaan dat de gebruiker een instructie heeft gehad? Dan kunnen we ervoor zorgen dat je niet meerdere keren het instructiescherm te zien krijgt.
> * Willen we het adviesscherm ook laten zien tijdens single table mode, of is de knop op de ViewHandPage dan genoeg? Kan me voorstellen dat single table "advanced" is, dus dat we er dan van uitgaan dat de gebruiker het scherm al een keer heeft gezien.
> * Misschien is het een idee om onderaan de instructiepagina nog even te laten zien hoe je de pagina terug kan vinden (iets van een kleine foto van de help button met als tekst dat dit tijdens het scannen gevonden kan worden)

Goed idee om onderaan te laten zien hoe je de pagina terug kan vinden. 
Verder denk ik dat het adviesscherm niet nodig is voor single table.. Ik zal even kijken naar de store om het op te slaan dat iemand al een keer de instructie gezien heeft.

2023-06-24 20:55 UTC, tvdplas approved these changes
Laatste nitpick, maar als je die autocorrect met github heb je mn approve

2023-06-24 20:55 UTC, tvdplas commented on src/views/Scan/AdviceScreen.vue
> +        </ion-title>
Stappenplan is één woord
```suggestion
        <ion-title>
          Stappenplan scannen
        </ion-title>
```

2023-06-24 20:55 UTC, tvdplas commented on src/views/Scan/AdviceScreen.vue
> +    </ion-content>
Dit is echt een goeie oplossing, nice!

2023-06-25 07:59 UTC, tvdplas requested changes

2023-06-25 07:59 UTC, tvdplas commented on src/views/Scan/ViewHandPage.vue
> +              /></card-select>
Je merge is niet helemaal goed gegaan. Suggestie zou t moeten fixen
```suggestion
              <card-select 
                :current="detections.map(x => x.card)"
                @cancel="isCardModalOpen = false;" 
                @card="(card: Card) => { isCardModalOpen = false; addCard(card) }"
              />
```

2023-06-25 08:06 UTC, merged