scan uitgebreid
Redoublet-org/Redoublet-app pull request #7
Opened 2023-03-16 12:49 UTC by rjvandel

Pagina's van scan uitgebreid

2023-03-17 18:58 UTC, TheGoldenFyre requested changes

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/ScanEastPage.vue
> +        },
Misschien is het handig om iets van een indicatie toe te voegen aan de interface dat dit de verwachte format is van een kaart value, want ik dacht dat het niet werkte omdat ik "Heer"/"King" in probeerde te vullen

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/ScanEastPage.vue
> +            card: {
Misschien is het handig om hier nog een keer te checken of een kaart valid is, want je kan op het moment waarde > 10 zonder problemen toevoegen

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/ScanEastPage.vue
> +            <ion-img :src="photo.webviewPath"></ion-img>
Typescript compiler geeft een error omdat de key niet het juiste type is. Kan opgelost worden door `:key="(photo as unknown) as string"` te doen (eerst casten naar unknown typen en vervolgens naar string, direct mag niet blijkbaar? beetje skeer)

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/ScanEastPage.vue
> +          this.$refs.item.$el.classList.add('ion-touched')
voor alle `this.$refs.item` zooi zelfde als comment hierboven

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/information.ts
Misschien bestand en interface iets duidelijkere naam geven die aangeeft dat dit de informatie is die tussen scanpagina's moet worden doorgegeven

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/ScanEastPage.vue
> +      },
Door dit zo in te lezen zorgt het ervoor dat de pagina een reference heeft naar het exampleCards object; een kaart handmatig toevoegen en doorgaan naar de volgende pagina zorgt en nu voor dat de toegevoegde kaart blijft staan. Wss niet een ramp aangezien het nu alleen een example is, maar wel iets om rekening mee te houden voor de uiteindelijke versie :)

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/GameDetailsPage.vue
> +        //const vulnerability = (document.getElementById("vulnerable") as HTMLInputElement)?.value as string;
comment en witregel kan weg

2023-03-17 18:58 UTC, TheGoldenFyre commented on src/views/Scan/ScanEastPage.vue
> +      <ion-modal ref="modal" trigger="open-modal">
Om even terug te komen op je appje: het lijkt erop dat een modal alleen getriggered kan worden als de id van het element uniek is tussen verschillende pagina's? idk wat er precies aan de hand is want het leek erop alsof ie alleen getriggerd kon worden door de eerste pagina met die id erop.  
Je kan het fixen door per pagina een andere id en trigger te gebruiken, ik heb bijvoorbeeld `id="open-modal-e", trigger="open-model-e"` gedaan op deze pagina (en hetzelfde voor de richtingen op de andere pagina's) en toen leek het consistent te werken

2023-03-21 21:10 UTC, TheGoldenFyre requested changes
Paar hele kleine dingetjes nog maar ziet er verder goed uit, lekker bezig!

2023-03-21 21:10 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +    }
Is dit nog nodig? Of kan je de definitie van detections vervangen met `let detections = reactive<Detection[]>(exampleCards.detections)`

2023-03-21 21:10 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +        }
code formatting

2023-03-21 21:10 UTC, TheGoldenFyre commented on src/views/Scan/ViewHandPage.vue
> +        const cardToBeAdded = {
Functienaam nog even aanpassen

2023-03-22 10:41 UTC, sebas42069 requested changes
wat stijling veranderingen

2023-03-22 10:41 UTC, sebas42069 commented on src/models/card.ts
> +        default:    throw "Not a valid value"
hier nog een ; na de throw

2023-03-22 10:41 UTC, sebas42069 commented on src/router/index.ts
> +import { routes as joinRoutes } from './join-tour'
imports ook eindigen met een ;

2023-03-22 10:41 UTC, sebas42069 commented on src/router/index.ts
>  })
variabelen ook eindigen met ;

2023-03-22 10:41 UTC, sebas42069 commented on src/views/Scan/GameDetailsPage.vue
> +    IonLabel } from '@ionic/vue';
deze bracket ook op nieuwe regel

2023-03-22 10:41 UTC, sebas42069 commented on src/views/Scan/ViewHandPage.vue
> +    const bothFieldsFilledIn = computed (() => newSuit.value != "" && newValue.value != "" && validateValue())
mist een ;

2023-03-22 10:41 UTC, sebas42069 commented on src/views/Scan/ViewHandPage.vue
> +    import { Detection } from './detection'
mist een ;

2023-03-22 10:41 UTC, sebas42069 commented on src/views/Scan/allHands.ts
> +    id : number,
hoort dit zo met ; en ,?

2023-03-22 10:58 UTC, TheGoldenFyre approved these changes

2023-03-22 10:59 UTC, sebas42069 approved these changes

2023-03-22 11:40 UTC, merged