UI aangepast
Redoublet-org/Redoublet-app pull request #71
Opened 2023-06-25 15:22 UTC by rjvandel

Let op:
Volgens mij klopt de bordentelling niet. Daar moeten we even naar kijken.

2023-06-25 15:40 UTC, tvdplas requested changes
Lekker bezig geweest! Ik heb nog wel een aantal opmerkingen over de styling, maar een deel is ook voorkeur, dus wees niet bang om gwn met me te bespreken! :)

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/SingleTablePage.vue
> +      </div>
Misschien beter om hier gewoon te zeggen dat alleen de namen zijn?
```suggestion
      <div class="h-align"> 
        <div class="orange-box">
          <h2>Voer de namen van de spelers in:</h2>
        </div>
      </div>
```

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/SingleTablePage.vue
![image](https://github.com/Redoublet-org/Redoublet-app/assets/20602812/0fbea3ef-3508-4243-a886-572e0089c91a)
Misschien mooi om die naam invoer boxes dezelfde breedte te geven als de header boxes

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +      </div>
Misschien om hierboven nog een aparte info box te hebben met [Voer de informatie in voor bord #xxx] (beetje vervanging van de titel van de pagina, aangezien die niet zo erg opvalt)

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +        <ion-title>Inofrmatie bord #{{ boards.boards.length + 1}}</ion-title>
+1 kan hier weg
```suggestion
        <ion-title>Inofrmatie bord #{{ boards.boards.length}}</ion-title>
```

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/EnterBoardPage.vue
> +          </ion-select>
Ik weet niet zeker of leider nou een echt veelgebruikte bridgeterm is, van wat ik zie is het vaker gewoon Dealer. Rest van de app (DDS voor de scan) gebruikt ook nog de term Dealer. Miss handig om het hier dan ook even gelijk te trekken. 
(Dit is mijn schuld btw, maar aangezien de PR toch al deze code aanpast kan het net zo goed direct worden aangepast :) )

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/EnterBoardPage.vue
![image](https://github.com/Redoublet-org/Redoublet-app/assets/20602812/b7379d6a-aeb5-4567-b325-289277d382de)
Zelfde met de width van de invoerboxes geldt hier ook. Miss ook even kijken of het mogelijk is om de dropdowns iets breder te maken, want de preview text wordt nu grotendeels afgesneden terwijl er nog best wat witruimte links ervan beschikbaar is

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/EnterBoardPage.vue
![image](https://github.com/Redoublet-org/Redoublet-app/assets/20602812/8ab47a1a-b34a-4482-89ec-25b7b0e62883)
Deze display voelt  een beetje raar aan, misschien is het een  optie om resultaat naar de contract sectie te verschuiven en dan van de laatste sectie gewoon een aparte "Eerste kaart" te maken? Dan kan je kleur en waarde gewoon apart vragen, en zien alle invoeren er hetzelfde uit

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/SingleTableScore.vue
![image](https://github.com/Redoublet-org/Redoublet-app/assets/20602812/eea1bdb4-5759-4fe3-bb92-d847eb60b8b6)
Kan je kijken of je hier de alignment iets anders kan doen? Ik denk dat het mooier is als alle labels left-aligned zijn, en de waardes right-aligned.
Geldt voor alle boxes

2023-06-25 15:40 UTC, tvdplas commented on src/views/SingleTableTournament/SingleTableScore.vue
![image](https://github.com/Redoublet-org/Redoublet-app/assets/20602812/48303d67-5f8c-4266-a072-48efeb27253a)
Tekst valt snel van de knoppen af, misschien iets korter maken of ervoor zorgen dat de tekst kan wrappen.
Daarnaast is het misschien fijn om hier iets consistenter te zijn met de kleuren en de hoogte van knoppen, zie evt de nieuwe viewhandpage (die heeft ook zo'n vaste knop aan de onderkant)

2023-06-26 20:01 UTC, tvdplas requested changes
Ziet er goed uit! Nog een dingetje over de declarer, maar dat lijkt m wel te zijn.

Back buttons die niet helemaal naar behoren werken doen we wel even in een losse PR morgen

2023-06-26 20:01 UTC, tvdplas commented on src/views/SingleTableTournament/SingleTableScore.vue
> +            </ion-item>
Hier even opletten met de declarer; we hebben die weggehaald omdat we dachten m niet meer te gebruiken, maar hier komt ie blijkbaar nog wel voor. Dan moeten we m wss wel opvragen

2023-06-27 07:53 UTC, rjvandel commented on src/views/SingleTableTournament/SingleTableScore.vue
> +            </ion-item>
jaa we hebben heel lelijk bij enterboardpage gwn de declarer value de dealer value gegeven hihaho

2023-06-27 08:32 UTC, tvdplas approved these changes

2023-06-27 08:33 UTC, merged